### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by Larzack** [mittwald/kubernetes-replicator#11] opened 2019-06-28 17:46 UTC
Hi,

I create a TLS secret in a dedicated Namespace, with the type: kubernetes.io/tls

When I sync with Kubernetes-replicator, the secret is Opaque and is not working..

How to replicate with the correct type ?

**Comment by martin-helmich** [comment] 2019-07-08 19:38
Hey @Larzack,

thanks for the report. Just to clarify:

Is your target secret :one: initially of type `kubernetes.io/tls` and _changes_ to `opaque` when replicated, or was it :two: created as `opaque` to begin with and does not update its type correctly?

In case of the former: That's bad. That should not happen and should be fixed.
In case of the latter: Changing the type of an existing secret is not possible, since this field is handled as immutable by the Kubernetes API server. In order to replicate a TLS secret (or other "special" types, like Docker login tokens or such), the receiving secret object needs to be of that type to begin with.

**Comment by Larzack** [comment] 2019-07-08 19:50
Hi Martin,

Option 1.

**Comment by dreh23** [comment] 2019-07-17 13:08
We used this and it seems to work:

```
apiVersion: v1
kind: Secret
metadata:
  name: wildcard.mydomain.com
  annotations:
    replicator.v1.mittwald.de/replicate-from: default/wildcard.mydomain.com
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""
```

**Comment by martin-helmich** [comment] 2020-01-09 06:47
Hey all -- sorry for the late response. I've confirmed that the way described by @dreh23  works for replicating TLS secrets.

For the time being, I'll adjust the README to reflect this "special" case. In the long run, we might come up with a more elegant solution to this.

**Closed** 2020-01-09 08:05 UTC
